# Generated by Django 5.1 on 2024-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_alter_customer_address_alter_seller_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="address",
            new_name="street",
        ),
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.IntegerField(),
        ),
    ]
