# Generated by Django 5.1 on 2024-08-29 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_rename_address_address_street_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid postal code. Format: '12345' or '12345-6789'.",
                        regex="^[0-9]{5}(?:-[0-9]{4})?$",
                    )
                ],
            ),
        ),
    ]
