# Generated by Django 5.1 on 2024-08-30 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_order_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cart_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_item",
                to="profile.cartitem",
            ),
        ),
    ]
