# Generated by Django 5.1 on 2024-08-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_remove_order_product_remove_orderitem_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="cart_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="profile.cartitem",
            ),
        ),
    ]
