# Generated by Django 5.1 on 2024-09-04 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0009_cartitem_customer_alter_address_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="profile.customer",
            ),
        ),
    ]
