# Generated by Django 5.1 on 2024-09-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0010_alter_cart_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="profile.customer",
            ),
        ),
    ]
