# Generated by Django 5.1 on 2024-09-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0010_alter_cartitem_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="customer",
        ),
    ]
