# Generated by Django 5.1 on 2024-09-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0014_remove_cartitem_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="profile.customer",
            ),
            preserve_default=False,
        ),
    ]
