# Generated by Django 5.0.7 on 2024-09-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0011_remove_cartitem_customer"),
        ("profile", "0016_alter_address_phone_number_alter_address_postal_code"),
    ]

    operations = []
