# Generated by Django 5.1 on 2024-09-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0016_alter_address_phone_number_alter_address_postal_code"),
        ("shop", "0007_alter_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(
                related_name="carts", through="profile.CartItem", to="shop.product"
            ),
        ),
    ]
