# Generated by Django 5.1 on 2024-09-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0018_remove_cart_product_cart_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="customer",
        ),
    ]
