# Generated by Django 5.1 on 2024-09-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0011_remove_cartitem_customer"),
        ("profile", "0019_remove_cart_product_remove_cartitem_customer"),
    ]

    operations = []
