# Generated by Django 5.1 on 2024-09-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0020_merge_20240905_0859"),
        ("shop", "0008_merge_20240905_0859"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="products",
            field=models.ManyToManyField(related_name="sellers", to="shop.product"),
        ),
    ]
