# Generated by Django 5.1 on 2024-09-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0021_seller_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="products",
        ),
    ]
