# Generated by Django 5.0.7 on 2024-09-17 09:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="https://fakeimg.pl/300x200",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
