# Generated by Django 5.1 on 2024-09-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_description_alter_product_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="image_url",
        ),
    ]
