# Generated by Django 5.1 on 2024-09-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_stock"),
        ("shop", "0005_rename_image_productimage_image_url"),
    ]

    operations = []
