# Generated by Django 5.1 on 2024-09-05 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="dummy", max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
