# Generated by Django 5.0.7 on 2024-09-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_stock"),
        ("shop", "0006_alter_product_stock"),
    ]

    operations = []
