# Generated by Django 5.1 on 2024-09-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_stock"),
        ("shop", "0007_alter_product_stock"),
    ]

    operations = []
