# Generated by Django 5.0.7 on 2024-09-13 11:34

import cloudinary.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_merge_20240911_0915"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default=django.utils.timezone.now, max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
