# Generated by Django 5.0.7 on 2024-09-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_productimage_image_url_productimage_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(default="http://via.placeholder.com/400x600"),
            preserve_default=False,
        ),
    ]
