# Generated by Django 5.0.7 on 2024-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_remove_productimage_image_productimage_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(default="https://fakeimg.pl/300x200"),
        ),
    ]
